name: CI

on: 
  push:

jobs:
  build-and-test-package:
    strategy:
      fail-fast: true 
      matrix:
        os: ["ubuntu-latest"]
        include:
          - os: ubuntu-latest
            environment-file: env.yml
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Run formatter
      uses: psf/black@stable
      if: matrix.os == 'ubuntu-latest'
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    # - name: Run linter
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install dependencies on ${{ matrix.os }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: filteresgf
        environment-file: ${{ matrix.environment-file }}
        python-version: 3.10
        auto-activate-base: false
    - name: Install esgffilterer
      shell: bash -l {0}
      run: python -m pip install .[tests]
    - name: Run tests on ${{ matrix.os }}
      shell: bash -l {0}
      run: pytest -s --disable-warnings tests